OWNERS

UPSTREAM: <carry>: openshift: Update owners

---

Dockerfile

Upstream: <carry>: openshift: Add docker images for CI

---

pkg/cloud/azure/actuators/machine/reconciler.go

Set the internal DNS name given by Azure-provided name resolution.
The name consists of a hostname (given by computer name) and internal
domain name suffix.
See https://docs.microsoft.com/cs-cz/azure/virtual-network/virtual-networks-name-resolution-for-vms-and-role-instances#azure-provided-name-resolution
In my testing environment I got the following internal DNS name:
```json
{
"address": "master-machine.54ldpetbazpu1nmrujpjuoo3vg.cx.internal.cloudapp.net",
"type": "InternalDNS"
}
```
where `master-machine` becomes the hostname and `54ldpetbazpu1nmrujpjuoo3vg.cx.internal.cloudapp.net` the internal DNS suffix.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR …

UPSTREAM: <carry>: openshift: Set internal DNS name

---

cmd/manager/main.go

Add `--namespace` flag to restrict the machine namespace to watch.
Fixes #
```release-note
```

UPSTREAM: <carry>: openshift: Add namespace flag

---

README.md
config/bootstrap.sh
config/controllers/deployment.yaml
config/generate-bootstrap.sh

UPSTREAM: <carry>: openshift: describe how to deploy machine API with azure machine controller over kubernetes

---

pkg/cloud/azure/actuators/machine/actuator_test.go
pkg/cloud/azure/actuators/machine/reconciler.go

UPSTREAM: <carry>: openshift: Expect vnet and managed identity to be always set

---

pkg/apis/azureprovider/v1alpha1/zz_generated.deepcopy.go

UPSTREAM: <carry>: openshift: run 'make generate'

---

Makefile

UPSTREAM: <carry>: openshift: Remove dep on bazel binary when running test-e2e target

---

pkg/apis/azureprovider/v1beta1/azuremachineproviderconfig_types.go

Add omitempty tag so empty strings are omitted from the output

UPSTREAM: <carry>: openshift: Add omitempty tag so empty strings are omitted from the output

---

hack/verify_history.sh

UPSTREAM: <carry>: openshift: create git history verification script

---

pkg/cloud/azure/actuators/machine/reconciler.go

The generated name is longer than allowed by the Azure portal under following OR conditions:
- machine name is changed (can't happen without creating a new CR)
- cluster name is changed (could happen but then we will get different name anyway)
- machine CR was created with too long public ip name (in which case no instance was created)
- machine config was edited and the publicIP field was set to true (no public ip resource is created after an instance was created)
In all cases there is nothing to delete. So the deletion can be skipped.
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1737505
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets …

UPSTREAM: <carry>: openshift: Skip deletion of public IPs with too long names

---

pkg/cloud/azure/services/internalloadbalancers/internalloadbalancers.go
pkg/cloud/azure/services/networkinterfaces/networkinterfaces.go
pkg/cloud/azure/services/subnets/subnets.go

UPSTREAM: <carry>: openshift: Apply 'make goimports'

---

Gopkg.lock
vendor/github.com/openshift/cluster-api/Makefile
vendor/github.com/openshift/cluster-api/hack/goimports.sh
vendor/github.com/openshift/cluster-api/pkg/controller/machine/controller.go

Revendor to bring https://github.com/openshift/cluster-api/pull/72

Bug 1752088: UPSTREAM: <carry>: openshift: Revendor to bring https://github.com/openshift/cluster-api/pull/72

---

pkg/cloud/azure/actuators/machine/actuator.go
pkg/cloud/azure/actuators/machine/actuator_test.go
pkg/cloud/azure/actuators/machine_scope.go
pkg/cloud/azure/actuators/scope.go

When appropriate fail with InvalidMachineConfiguration during instance
creation.

Fail with InvalidMachineConfiguration in Create

---

pkg/cloud/azure/actuators/machine/actuator.go
pkg/cloud/azure/actuators/machine/actuator_test.go

bug 1770128: UPSTREAM: <carry>: openshift: Fix statusCode conversion

---

.gitignore
Makefile

This PR adds: `bin/` directory to gitignore and `build` task to makefile

Improve makefile and gitignore

---

go.mod
go.sum
vendor/github.com/openshift/machine-api-operator/pkg/apis/machine/v1beta1/machinehealthcheck_types.go
vendor/github.com/openshift/machine-api-operator/pkg/controller/machine/controller.go

Revendor mao with timeout formatting fix https://github.com/openshift/machine-api-operator/pull/495

Revendor mao with timeout formatting fix

---

pkg/cloud/azure/services/networkinterfaces/networkinterfaces.go

This adds support for detecting IPv6 address space on the subnet for a
new machine, and automatically adding a private IP configuration with
a dynamic address from that space.

Bug 1803844: Support private IPv6 address configurations

---

go.mod
go.sum
vendor/github.com/openshift/machine-api-operator/pkg/controller/machine/controller.go
vendor/modules.txt

Revendor MAO to add unknown state for externally removed machines

Bug 1808971: Machine status shows "running" when an instance was terminated

---

pkg/cloud/azure/services/virtualmachines/virtualmachines.go

Bug 1845610: Windows VM MachineSet error on Azure

---

Dockerfile
Makefile
go.mod
hack/goimports.sh
vendor/modules.txt

Unblocks https://github.com/openshift/release/pull/13785

[OCPCLOUD-977] Bump scripts to Go 1.15

---

hack/verify_history.sh

I've copied this updated script from the autoscaler repository. The update means that you no longer need `openshift:` in the prefix and, if you get the prefix wrong, we actually print out a message to tell you why and how to fix it.
Doing this so that the verify history script is consistent across repositories

Update Git History check script to align with othwr repositories

---

Makefile
hack/go-mod.sh

Enables vendoring in container. Adds option to run make vendor in container like other targets, to avoid issues with go module caching depending on what you already have on your machine.
Fixes #
```release-note
```

add in container vendor

---

pkg/apis/azureprovider/v1beta1/types.go
pkg/cloud/azure/services/virtualmachines/virtualmachines.go
pkg/cloud/azure/services/virtualmachines/virtualmachines_test.go

Manual backport of #243 
Adding support for marketplace images.

Bug 2027896: [release-4.8] Add support for Azure Marketplace Images

---

openshift/verify-history.sh

Adds verify-history.sh for use in CI

Add verify-history

---

.snyk

Hello! This is a PR to add a snyk file to exclude the vendors folder while scanning the repo. Thanks!

OCPBUGS-25626: Add Snyk file to exclude vendor directory on scan

---

.snyk

This change adds a file to configure the automated snyk security scans.

OCPBUGS-27450: add a snyk configuration file

---

api/v1beta1/azuremachine_types.go
api/v1beta1/azuremachine_validation.go
api/v1beta1/azuremachine_webhook.go
api/v1beta1/azuremachine_webhook_test.go
api/v1beta1/azuremachinetemplate_webhook.go
api/v1beta1/azuremachinetemplate_webhook_test.go
api/v1beta1/zz_generated.deepcopy.go
azure/scope/machine.go
azure/scope/machine_test.go
azure/services/virtualmachines/spec.go
config/crd/bases/infrastructure.cluster.x-k8s.io_azuremachines.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_azuremachinetemplates.yaml

This is a downstream only backport for this feature. It will release in 1.16.0 upstream version.

OCPCLOUD-1640: Add DisableExtensionOperations field
