openshift/cluster-api-provider-azure

Gopkg.lock, pkg/apis/azureprovider/v1alpha1/azuremachineproviderconfig_types.go, pkg/apis/azureprovider/v1alpha1/zz_generated.deepcopy.go, pkg/cloud/azure/actuators/BUILD.bazel, pkg/cloud/azure/actuators/machine/BUILD.bazel, pkg/cloud/azure/actuators/machine/actuator_test.go, pkg/cloud/azure/actuators/machine/reconciler.go, pkg/cloud/azure/actuators/machine_scope.go, pkg/cloud/azure/services/virtualmachines/virtualmachines.go, vendor/sigs.k8s.io/controller-runtime/pkg/client/fake/BUILD.bazel, vendor/sigs.k8s.io/controller-runtime/pkg/client/fake/client.go, vendor/sigs.k8s.io/controller-runtime/pkg/client/fake/doc.go
…Secrets for Ignition
- Adds support for Customdata in vm
- Gets customdata from secret if provided
- Skip calling vm extension if custom data is provided
Fixes #
```release-note
Bootstrap using Custom Data specified in secrets
```
=> UPSTREAM: <carry>: openshift: Add support for Custom data, read from secrets for Ignition

pkg/apis/azureprovider/v1alpha1/types.go, pkg/cloud/azure/services/virtualmachines/virtualmachines.go
RHCOS images are never present in market place rather in alternative location, adds support for the same
Fixes #
```release-note
Support for Alternate OS Image location
```
=> UPSTREAM: <carry>: openshift: support for resourceid as an alternate image location

pkg/cloud/azure/actuators/machine/BUILD.bazel, pkg/cloud/azure/actuators/machine/actuator_test.go, pkg/cloud/azure/actuators/machine/reconciler.go, pkg/cloud/azure/defaults.go, pkg/cloud/azure/services/disks/BUILD.bazel, pkg/cloud/azure/services/disks/disks.go, pkg/cloud/azure/services/disks/service.go
- When a VM fails, its deleted and recreated again (azure specific)
- During deletion OS Disk is not cleaned up, causing it to permanently fail
- PR cleans up all supporting resources created by cluster api (owned)
Fixes #
```release-note
NONE
```
=> UPSTREAM: 202 : openshift: delete OS Disks and Network interface before creating new VM instance, else fails due to previous existence

pkg/cloud/azure/actuators/machine/BUILD.bazel, pkg/cloud/azure/actuators/machine/reconciler.go
Set hostname, private IP, public IP and external DNS name in machine.Status.Addresses.
The list of addresses is needed to approve a node and link a node with
it's corresponding machine.
Fixes #
```release-note
```
=> UPSTREAM: <carry>: openshift: Set machine addresses

pkg/cloud/azure/actuators/machine/reconciler.go, pkg/cloud/azure/defaults.go
Set ProviderID as is set in kubelet cloud providers, i.e. using the following template:
"azure:///subscriptions/SUBSCRIPTION/resourceGroups/RESOURCEGROUP/providers/Microsoft.Compute/virtualMachines/COMPUTERNAME".
It helps to match nodes and machines without relying on machine NodeRef field.
Fixes #
```release-note
```
=> UPSTREAM: <carry>: openshift: Set machine.Spec.ProviderID

pkg/cloud/azure/actuators/machine/BUILD.bazel, pkg/cloud/azure/actuators/machine/conditions.go, pkg/cloud/azure/actuators/machine/conditions_test.go, pkg/cloud/azure/actuators/machine/reconciler.go
instance failed to be created:
```
$ kubectl get machine master-machine -o json | jq ".status.providerStatus.conditions"
[
{
"lastProbeTime": "2019-06-03T10:56:42Z",
"lastTransitionTime": "2019-06-03T10:56:42Z",
"message": "failed to create nic master-machine-nic for machine master-machine: unable to create VM network interface: subnet os4-common-node-subnet-111 not found: network.SubnetsClient#Get: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code=\"NotFound\" Message=\"Resource /subscriptions/6648228a-736c-4a4e-9a14-92a7e5190f4a/resourceGroups/os4-common/providers/Microsoft.Network/virtualNetworks/os4-common-vnet/subnets/os4-common-node-subnet-111 not found.\" Details=[]",
"reason": "MachineCreationFailed", …
```
=> UPSTREAM: <carry>: openshift: Publish machine conditions during Create and Update operations

pkg/cloud/azure/actuators/machine/reconciler.go, pkg/cloud/azure/services/virtualmachines/virtualmachines.go
So the machine controller can reconcile multiple machines in (pseudo-)parallel manner.
During instance creation machine condition are updated
```
$ sudo kubectl get machine master-machine -o json | jq ".status.providerStatus.conditions"
[
{
"lastProbeTime": "2019-06-03T14:54:04Z",
"lastTransitionTime": "2019-06-03T14:54:04Z",
"message": "failed to create vm master-machine : vm master-machine is still in provisioningstate Creating, reconcile",
"reason": "MachineCreationFailed",
"status": "True",
"type": "MachineCreated"
}
]
```
Machine controller logs:
- E0603 17:07:49.092615   25083 actuator.go:106] failed to delete machine master-machine: failed to delete machine: compute.VirtualMachinesDeleteFuture: asynchronous operation has not completed
- E0603 16:56:06.318106   23883 actuator.go:79] …
=> UPSTREAM: <carry>: openshift: Allow to run Create/Delete ops async

pkg/apis/azureprovider/v1alpha1/azuremachineproviderconfig_types.go, pkg/cloud/azure/actuators/machine/actuator_test.go, pkg/cloud/azure/actuators/machine/reconciler.go, pkg/cloud/azure/services/networkinterfaces/networkinterfaces.go
Do not rely on machine.openshift.io/cluster-api-machine-role label to determine
subnet name. Instead, use specific subnet so different worker machine groups
can have different subnet.
Fixes #
```release-note
```
=> UPSTREAM: <carry>: openshift: Set instance subnet and load balancers explicitly

pkg/apis/azureprovider/v1alpha1/azuremachineproviderconfig_types.go, pkg/cloud/azure/actuators/machine/reconciler.go, pkg/cloud/azure/defaults.go
Once installer sets both fields explictly, have machine azure actuator to require them
and fail when they are not set.
Fixes #
```release-note
```
=> UPSTREAM: <carry>: openshift: Allow vnet and managed identity names to be set explicitly

Dockerfile
=> UPSTREAM: <carry>: openshift: Switch builds to use Go 1.12

pkg/apis/azureprovider/v1alpha1/azuremachineproviderconfig_types.go, pkg/cloud/azure/actuators/machine/reconciler.go
Currently the provider, randomly chooses the Zones for a machine.
* The user must have the capability to choose the zone.
* Also allow the user to use the previous behaviour of NO zone for the machine.
The current implementation for IPI Azure does not use Availability Zones for IPI. The installer needs a way to enforce that on the machines.
=> UPSTREAM: <carry>: openshift: allowing choosing availability zone for a machine

Gopkg.lock, vendor/github.com/openshift/kubernetes-drain/drain.go
Running "dep ensure -update github.com/openshift/kubernetes-drain"
This commit fixes a bug where drain does not wait for
completion of eviction or deletion of pods due to
missing namespace attribute when checking if pod still
exists after drain operation.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1729512
Fixes #
```release-note
```
=> UPSTREAM: <carry>: openshift: Update vendored github.com/openshift/kubernetes-drain

pkg/apis/azureprovider/v1alpha1/azureclusterproviderconfig_types.go, pkg/apis/azureprovider/v1alpha1/azuremachineproviderconfig_types.go, pkg/cloud/azure/actuators/machine_scope.go, pkg/cloud/azure/services/subnets/subnets.go, pkg/cloud/azure/services/virtualnetworks/virtualnetworks.go
Allow for separate Network resource group
The goal is to allow networking components like the subnets, VNET to
be in a separate resource group but the resources for the cluster like
LBs, network interfaces, VMs, etc stay in the resource group of the
cluster.
The following services remain in the existing `ResourceGroup`:
- availabilityzones
- certificates
- config
- disks
- groups
- internalloadbalancers
- networkinterfaces
- publicips
- publicloadbalancers
- routetables
- securitygroups
- virtualmachineextensions
- virtualmachines
The following services are now in the new `NetworkResourceGroup`:
- subnets
- virtualnetworks
https://jira.coreos.com/browse/CLOUD-594
=> Allow for separate Network resource group

pkg/apis/azureprovider/v1alpha1/azuremachineproviderconfig_types.go, pkg/cloud/azure/actuators/machine/BUILD.bazel, pkg/cloud/azure/actuators/machine/actuator_test.go, pkg/cloud/azure/actuators/machine/reconciler.go
This changes default behaviour to be deterministic and to give explicit control to the user over using zones or not and which one to choose instead of deploying to a random a zone by default. We want to provide as similar as possible user experience between cloud providers. Although in the future actuators might get smarter or/and integrate with provider specific sets/asg we design and assume for them being dumb simple and control is given to the user via inputs.
We don't want to cause the impression that actuator is smart and would smartly choose zones for you. Default behaviour should be explicit and deterministic, then as consumers we architect our solution on top to ensure we spread across zones evenly.
Orthogonal to https://github.com/openshift/installer/pull/1949#issuecomment-5095907 …
=> UPSTREAM: <carry>: openshift: Change behaviour for zones and add unit tests

pkg/cloud/azure/services/disks/disks.go, pkg/cloud/azure/services/virtualmachines/virtualmachines.go
So the machine controller can delete multiple disks in (pseudo-)parallel manner.
Fixes #
```release-note
```
=> UPSTREAM: <carry>: openshift: Allow to run disk delete ops async

Makefile, hack/e2e.sh
Allows `make test-e2e` from CI to work.
=> Makefile: add e2e machinations

pkg/cloud/azure/actuators/machine/actuator.go, pkg/cloud/azure/actuators/machine_scope.go
Polish machine lifecycle workflow
- Rename close to store and make it error aware and to fail explicitly rather than defering and hope for the best.
=> UPSTREAM: <carry>: openshift: Rename close to persist, make it error aware, stop persisting on exist

pkg/cloud/azure/actuators/machine/reconciler.go
Remove mutating logic from Exist(). Mutating logic on exists is semantically wrong as well as it leads to stale objects api update issues, given the machine controller workflow design. The machine controller workflow always heads towards
`if exist then update` any mutating logic other than status should preferably belong to `update` so it will become eventually consistent.
Follow up for https://github.com/openshift/cluster-api-provider-azure/pull/61
=> UPSTREAM: <carry>: openshift: Remove mutating logic from exist and set vm state in update

pkg/cloud/azure/actuators/BUILD.bazel, pkg/cloud/azure/actuators/machine_scope.go, pkg/cloud/azure/actuators/machine_scope_test.go
Use location from API over secret and unit test. In follow ups we might want to drop location and resource group from the secret
=> UPSTREAM: <carry>: openshift: Use location from API over secret and unit test

pkg/apis/azureprovider/v1beta1/azuremachineproviderconfig_types.go, pkg/apis/azureprovider/v1beta1/zz_generated.deepcopy.go, pkg/cloud/azure/actuators/machine/reconciler.go, pkg/cloud/azure/services/virtualmachines/BUILD.bazel, pkg/cloud/azure/services/virtualmachines/virtualmachines.go, pkg/cloud/azure/services/virtualmachines/virtualmachines_test.go
All of the clouds allow you to tag their VMs with metadata tags.  So you can filter and do a ton of other activities that fall out of having tags.
We want to expose a tags field on the API on azure and honour it on the actuator implementation for machines.
=> UPSTREAM: <carry>: openshift: Add support for machine tags

pkg/cloud/azure/actuators/machine/BUILD.bazel, pkg/cloud/azure/actuators/machine/reconciler_test.go
Add unit test for `exists()`
Follow up for https://github.com/openshift/cluster-api-provider-azure/pull/62
=> UPSTREAM: <carry>: openshift: Add unit test for exists()

pkg/cloud/azure/actuators/machine/reconciler.go
E0817 08:16:19.223388       1 runtime.go:69] Observed a panic: "assignment to entry in nil map" (assignment to entry in nil map)
/go/src/sigs.k8s.io/cluster-api-provider-azure/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:76
/go/src/sigs.k8s.io/cluster-api-provider-azure/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65
/go/src/sigs.k8s.io/cluster-api-provider-azure/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51
/usr/local/go/src/runtime/panic.go:522
/usr/local/go/src/runtime/map_faststr.go:204
/go/src/sigs.k8s.io/cluster-api-provider-azure/pkg/cloud/azure/actuators/machine/reconciler.go:425
/go/src/sigs.k8s.io/cluster-api-provider-azure/pkg/cloud/azure/actuators/machine/actuator.go:140
/go/src/sigs.k8s.io/cluster-api-provider-azure/vendor/github.com/openshift/c …
=> Check if annotations are initialized before assigning a key

pkg/cloud/azure/actuators/machine/reconciler.go, pkg/cloud/azure/defaults.go, pkg/cloud/azure/defaults_test.go
Generated ip public name has to be the same all the time since the name is generated in two different operations (Create and Delete) which are independent of each other. Unless the public ip name is stored in machine status, the delete has to get the same name as the create operation to delete the resource from Azure.
Fixes #
```release-note
```
=> UPSTREAM: <carry>: openshift: do not randomize public ip name, error instead

Makefile, hack/goimports.sh, pkg/cloud/azure/mock/client_generated.go, pkg/cloud/azure/services/internalloadbalancers/internalloadbalancers.go, pkg/cloud/azure/services/networkinterfaces/networkinterfaces.go, pkg/cloud/azure/services/subnets/subnets.go
So the target can be run in CI and fail in case files are not properly goimport formated.
=> UPSTREAM: <carry>: openshift: Extend makefile with 'make goimports' target

pkg/cloud/azure/actuators/machine/actuator.go
Multiple of a minute is too wide window to wait for a machine to be created
in case the instance creation fails. In practice, it's between 2 minutes and
3 minutes (closer to 2 minutes). Resyncing the machines 3 times faster will
also help to pop machines from the queue sooner and improve actuator's response
when creating hundreds of machines simultaniously.
Fixes #
```release-note
```
=> UPSTREAM: <carry>: openshift: Resync every 20 seconds

pkg/cloud/azure/actuators/machine/actuator_test.go, pkg/cloud/azure/actuators/machine/reconciler.go
So all machines owned by a cluster are easily recognizable
without relying on instance name prefix/suffix.
```sh
$ az vm list -g jchaloup-njzl2-rg | jq '.[] | (.name) + "    " + (.tags|tostring)'
"jchaloup-njzl2-master-0    {}"
"jchaloup-njzl2-master-1    {}"
"jchaloup-njzl2-master-2    {}"
"jchaloup-njzl2-worker-centralus1-2hj5s    null"
"jchaloup-njzl2-worker-centralus1-5nndn    {\"kubernetes.io-cluster-jchaloup-njzl2\":\"owned\"}"
"jchaloup-njzl2-worker-centralus2-kj2md    null"
"jchaloup-njzl2-worker-centralus3-zcsd7    null"
```
Fixes #
_Please confirm …
=> UPSTREAM: <carry>: openshift: tag instances with cluster id

pkg/apis/azureprovider/v1beta1/azuremachineproviderconfig_types.go, pkg/cloud/azure/actuators/machine/reconciler.go, pkg/cloud/azure/services/applicationsecuritygroups/applicationsecuritygroups.go, pkg/cloud/azure/services/applicationsecuritygroups/service.go, pkg/cloud/azure/services/networkinterfaces/networkinterfaces.go
Updates the machine spec to allow setting the security group and application security groups for machine
Firewall on Azure is controlled by network security groups. NSGs can be attached at the subnet level or can be attached to individual network interfaces.
attaching the NSG to subnets allows controlling firewall for all resources in the subnet, but only *ONE* NSG can be attached to a subnet. The lack of composition is especially bad for openshift installer when users want to install the cluster to some pre-existing subnets. 
The installer cannot create isolation boundaries for the cluster from other resources in the same subnet as the installer cannot update the subnet level NSG as that is not appropriate for shared subnet.
attaching the NSG to …
=> CLOUD-670: allow setting the security group and application security groups for machine in spec

pkg/cloud/azure/services/networkinterfaces/networkinterfaces.go
Previosly (https://github.com/openshift/cluster-api-provider-azure/commit/d1d0550184fc223cffae172623e856415ae2f4cd#diff-163ea357c91ff9f422b314e3b60e84f7R161-R173), the groups ID slice was initialized to the len to ASG names, and then append was used to add ASG IDs, which causes the group ID slice to contain empty IDs and then appended required IDs.
The fix initializes the group ID slice to empty to correctly append.
```release-note
```
=> UPSTREAM: <carry>: openshift: services/networkinterfaces: fix application security group collection

pkg/cloud/azure/actuators/machine/reconciler.go
Allow Azure VMs to be created without managed identity set.  Although this won't be the case in the short term in generality for OCP on Azure, it is essential for Azure Red Hat OpenShift.
@enxebre @ingvagabund ptal, if this is controversial please can we discuss? :-)
We need to get this into release-4.3, please can you help me take the right steps to make this happen?  Many thanks.
=> Bug 1779666: Can't create Azure worker nodes without managed identity (4.4)

pkg/cloud/azure/actuators/machine/reconciler.go
Allow Azure VMs to be created without managed identity set. Although this won't be the case in the short term in generality for OCP on Azure, it is essential for Azure Red Hat OpenShift.
ref https://github.com/openshift/cluster-api-provider-azure/pull/95
=> Bug 1779665: Can't create Azure worker nodes without managed identity (4.3)

pkg/cloud/azure/actuators/machine_scope.go
Currently, the actual status never gets updated. First `Patch()` call updates machine, but doesn't update the status, which means that status remains outdated. The result of the first `Patch()` call is an updated machine with an outdated status. This result is saved to `machine` that we pass as an argument. When we call `Status().Patch()` later with the same machine, actual status never gets there.
The solution is to save status, before calling first `Patch()`
=> Bug 1796599: Save status before Patch()

pkg/cloud/azure/actuators/machine_scope.go
Remove modification of LastUpdate in machine scope. It should be changed by the core machine controller when "phasing" or by the node-link controller because we need to make it more consistent across all cloud providers.
=> Remove modification of LastUpdate in machine scope

pkg/cloud/azure/services/publicips/publicips.go
Remove fqdn from public ip creation. `s.Scope.Network()` always returns nil and this caused panic.
I will open a followup PR that removes unused code.
=> Bug 1809001: Remove fqdn from public ip creation

Makefile, hack/ci-test.sh
This PR restores the original behaviour of `make unit`, depends on https://github.com/openshift/release/pull/7755 being merged first
=> Restore original make unit behaviour

Dockerfile, Makefile, go.mod, hack/goimports.sh
Bump scripts and docker images to Go 1.13
=> UPSTREAM: <carry>: openshift: Bump to Go 1.13

pkg/cloud/azure/defaults.go, pkg/cloud/azure/defaults_test.go
When setting the ProviderID for a Machine, this sets the subscriptionID and the resourceGroupName to lowercase strings as in done in the upstream legacy-cloud-provider which sets ProviderIDs on Nodes.
This fixes an issue where users could configure their MachineSet with a capitalised resourceGroup (even though the API is case-insensitive) and then the ProviderID  on the Machine would not match the ProviderID on the Node, causing the autoscaler to believe the instance was unregistered
=> Bug 1837341: Use ToLower for Subscription ID and Resource Group Name

pkg/cloud/azure/defaults.go, pkg/cloud/azure/defaults_test.go
Cheery-pick of #134 onto the release-4.4 branch
=> [release-4.4] Bug 1841478: Use ToLower for Subscription ID and Resource Group Name

pkg/apis/azureprovider/v1beta1/azuremachineproviderconfig_types.go, pkg/cloud/azure/actuators/machine/reconciler.go
Start introducing spot instances to downstream by exposing them to provider spec and reconciling label
https://raw.githubusercontent.com/openshift/enhancements/master/enhancements/machine-api/spot-instances.md
=> Expose spot instances to provider spec and reconcile label

pkg/cloud/azure/actuators/machine/actuator.go, pkg/cloud/azure/actuators/machine/reconciler.go
We log `found vm for machine ...` when `Exists()` can return false. This PR should fix that.
=> Fix confusing log in azure

go.mod, go.sum, vendor/github.com/openshift/machine-api-operator/pkg/controller/machine/controller.go, vendor/modules.txt
Revendor MAO with timeout formatting fix in node draining log message.
=> [release-4.4] Bug 1810531: UPSTREAM: <carry>: openshift: Revendor MAO with timeout formatting fix

cmd/manager/main.go
Implemented leader election for azure provider
OCPCLOUD-492
Couple of new cli arguments for configuring leader election
```release-note
-leader-elect
Start a leader election client and gain leadership before executing the main loop. Enable this when running replicated components for high availability. (default true)
-leader-elect-lease-duration int
The duration that non-leader candidates will wait after observing a leadership renewal until …
```
=> OCPCLOUD-492: Run all machine api Controllers using leader election

Dockerfile, Makefile, cmd/termination-handler/main.go, pkg/cloud/azure/actuators/machine/reconciler.go, pkg/cloud/azure/actuators/machine/reconciler_test.go, pkg/termination/termination.go, pkg/termination/termination_suite_test.go, pkg/termination/termination_test.go
This PR adds a termination handler for spot instances. It is based on the termination handler that Joel wrote for AWS and has similar logic.
In order to get the termination notice, we should poll `scheduledevents` endpoint, unmarshal json and check for `Preempt` event 
https://github.com/openshift/cluster-api-provider-aws/pull/308
https://github.com/openshift/enhancements/blob/master/enhancements/machine-api/spot-instances.md
=> Add termination handler for spot instances

pkg/cloud/azure/actuators/machine/reconciler.go, pkg/cloud/azure/actuators/machine/reconciler_test.go
While attempting to create a spot VM, my providerspec `spotVMOptions: {}` got expanded to 
```
spotVMOptions:
maxPrice: ""
```
Not sure why this happened, it shouldn't have, need to work that out still, but it did lead to this error from the machine creation:
```
message: 'failed to create vm jspeed-test-n7vrfcqlpr-k4dcg: failed to get Spot
VM options strconv.ParseFloat: parsing "": invalid syntax'
```
This PR ensures that we ignore empty `MaxPrice` values and do not return an error in the case that the `MaxPrice` is for some reason, the empty string.
=> Ensure empty max price does not cause error when creating a spot VM

pkg/cloud/azure/actuators/machine/reconciler.go, pkg/cloud/azure/actuators/machine/reconciler_test.go
Adds additional tests for the setMachineCloudProviderSpecifics to improve testing scenarios
=> Extend testing of setMachineCloudProviderSpecifics

pkg/cloud/azure/actuators/machine/reconciler.go, pkg/cloud/azure/actuators/machine/reconciler_test.go
Currently, when a VM is being created in Azure, we first check whether the VM exists and then attempt to create it if not.
On the first attempt to create, we always get an asynchronous time out:
```
E0709 16:44:25.752572       1 actuator.go:78] Machine error: failed to reconcile machine "jspeed-test-8cnpg-worker-centralus3-g6htz"s: failed to create vm jspeed-test-8cnpg-worker-centralus3-g6htz: failed to create or get machine: compute.VirtualMachinesCreateOrUpdateFuture: asynchronous operation has not completed
```
This will cause the Machine to be requeued. Currently, because Exists does not determine the machine to exist, we attempt to create again and get the following error:
```
E0709 16:44:26.642473       1 actuator.go:78] Machine error: failed …
```
=> BUG 1836141: Assert VM exists if VM state is Creating

pkg/cloud/azure/actuators/machine/reconciler.go
Fail machine if create request doesn't succeed.
For spot instances when the max price is lower than the current spot price, we should fail the machine. Currently, we are constantly trying to provision it. Azure error types are not great, so I think this is the cleanest way to fail machines.
This approach will also fail the machines in other cases like reaching quota limits.
=> Bug 1860229: Fail machine if create request doesn't succeed

pkg/cloud/azure/actuators/machine/reconciler.go, pkg/cloud/azure/services/virtualmachines/virtualmachines.go
This commit adds functionality for automatically running
C:\AzureData\CustomData.bin on first boot.
This custom data file is provided via the user data secret,
and contains init scripts.
The Windows Machine Config Operator relies on the user data script being
started automatically on the Windows VM to set up SSH access.
On AWS, it is invoked automatically after provisioning.
This commit is intended to align Azure with that behavior.
I've tested this manually and verified it works.
Fixes #
_Please confirm that if this PR changes any image versions, then that's …
=> Bug 1881154: Add AdditionalUnattendContent on Windows machines

OWNERS
This change adds the bugzilla component and subcomponent names to the OWNERS file to
comply with the prodsec requirements for OpenShift builds through ART.
=> add bugzilla component and subcomponent to OWNERS

Makefile, hack/verify-diff.sh
Allowing automatic `make generate` checks in CI. It allows to keep track of API changes, client generated code updates on each PR.
Fixes #
This PR is dependent on https://github.com/openshift/release/pull/13400 to enable the functionality in CI.
```release-note
NONE
```
=> [OCPCLOUD-809] Add verify-diff check in generate task and enable in CI

pkg/termination/termination.go, pkg/termination/termination_test.go
Switch from deleting the Machine to marking the Node with a Terminating condition.
This will integrate with an MHC to ensure that the Machine is deleted.
This should be possible using the Node's credentials and as such, the termination handler will not need its own credentials and extra permissions.
Requires openshift/machine-api-operator#627 before it will work
openshift/cluster-api-provider-aws#332
=> [OCPCLOUD-1043] Bug 1902157: Update termination handler to use node conditions

Dockerfile.rhel
This replaces #194 with the correct git-history naming
Updating ose-azure-machine-controllers builder & base images to be consistent with ART
Reconciling with https://github.com/openshift/ocp-build-data/tree/3d1d49f1c8fabf829e5a88e575485c0091329ac2/images/ose-azure-machine-controllers.yml
If you have any questions about this pull request, please reach out to @art-team in the #aos-art coreos slack channel.
=> Updating ose-azure-machine-controllers builder & base images to be consistent with ART 

pkg/termination/termination.go
When creating an http request in go, this sets two goroutines in the background running. If the body is not closed properly, these goroutines are leaked. This leads to a gradual increase in memory used by the application over time. We must ensure we always close response bodies
=> Bug 1934021: Ensure response body is closed when we are finished with the request

pkg/cloud/azure/actuators/machineset/controller.go, pkg/cloud/azure/actuators/machineset/controller_test.go
Prevent endless reconciles for machineSet due to failed attempt to set scale from zero annotation when the instance type is missing in our static list.
=> Bug 1918910: Only log error on wrong instance type for scale from zero

pkg/cloud/azure/services/networkinterfaces/networkinterfaces.go, vendor/k8s.io/utils/net/ipnet.go, vendor/k8s.io/utils/net/net.go, vendor/k8s.io/utils/net/port.go, vendor/modules.txt
Current dual-stack support fails when there are loadbalancers associated to the VMs, because load balancers implement different backends per IP family.
This causes that when a loadbalancer with multiples IPs is associates to a dual stack VM, the VM interfaces is added to a backend with different IP family, causing that the VM can not be created
```
I0317 22:42:50.679720       1 networkinterfaces.go:188] Found IPv6 address space. Adding IPv6 configuration to nic: aojeadual-wzzqr-worker-centralus2-dzlvq-nic
I0317 22:42:51.230128       1 machine_scope.go:160] aojeadual-wzzqr-worker-centralus2-dzlvq: patching machine
E0317 22:42:51.295170       1 actuator.go:78] Machine error: failed to reconcile machine "aojeadual-wzzqr-worker-centralus2-dzlvq": …
```
=> Bug 1959479: UPSTREAM: <carry>: openshift: Fix dual stack support for machines with Load Balancers associated

pkg/apis/azureprovider/v1beta1/azuremachineproviderconfig_types.go, pkg/apis/azureprovider/v1beta1/zz_generated.deepcopy.go, pkg/cloud/azure/actuators/machine/reconciler.go, pkg/cloud/azure/actuators/machine/reconciler_test.go
Ticket description: `A bug was identified upstream in that go clients were hitting validation errors when trying to serialize the field. The solution they found upstream was to move the field to a resource.Quantity.`
Upstream PR: https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/1157
=> [OCPCLOUD-1108] Fix spot instances price type

pkg/cloud/azure/actuators/machine/actuator.go
Now Azure actuator always creates an event after Update, even though the change might not have happened.
To prevent creating fake events we compare machine resource version before and after update, and create an event only if they are different.
=> Bug 1988992: Create event only if the machine was modified

pkg/cloud/azure/actuators/machine/actuator_test.go, pkg/cloud/azure/actuators/machine/reconciler.go, pkg/cloud/azure/actuators/machine/reconciler_test.go, pkg/cloud/azure/services/availabilitysets/availabilitysets.go, pkg/cloud/azure/services/availabilitysets/service.go, pkg/cloud/azure/services/virtualmachines/virtualmachines.go, pkg/cloud/azure/services/virtualmachines/virtualmachines_test.go
This is useful when azure region does not have multiple zones but supports availability sets. Our controller will detect that the region has no zone and create an availability set for each machine set.
Note: availability set also gets deleted along with the resource group during cluster deletion.
=> [RFE-793] Create availability sets when needed

go.mod, go.sum, vendor/github.com/openshift/machine-api-operator/pkg/apis/machine/v1beta1/machine_webhook.go, vendor/github.com/openshift/machine-api-operator/pkg/apis/machine/v1beta1/machinehealthcheck_types.go, vendor/modules.txt, vendor/sigs.k8s.io/controller-tools/pkg/crd/markers/validation.go, vendor/sigs.k8s.io/controller-tools/pkg/crd/markers/zz_generated.markerhelp.go, vendor/sigs.k8s.io/controller-tools/pkg/crd/schema.go
Update the machine-api-operator dependency in order to enable Azure's accelerated networking.
=> Update machine-api-operator dependencies

pkg/cloud/azure/services/virtualmachines/virtualmachines.go
The `MachineSpec` allows passing the `imageReference` fields to specify an image from the Azure Marketplace:
```go
// ImageReference specifies information about the image to use. You can specify information about platform
// images, marketplace images, or virtual machine images. This element is required when you want to use a
// platform image, marketplace image, or virtual machine image, but is not used in other creation
// operations. NOTE: Image reference publisher and offer can only be set when you create the scale set.
type ImageReference struct {
// Publisher - The image publisher.
Publisher *string `json:"publisher,omitempty"`
// Offer - Specifies the offer of the platform image or marketplace image used to create the virtual machine.
Offer *string `json:"offer,omitempty"`
// Sku - …
```
=> Bug 2021322: Azure Marketplace Purchase Plan Info

pkg/cloud/azure/services/virtualmachines/virtualmachines.go
Reverts openshift/cluster-api-provider-azure#237
It was highlighted via slack that the current fix does not work for marketplace images that are free. This is causing issues for existing images that are using the marketplace, eg [WMCO CI](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_windows-machine-config-operator/777/pull-ci-openshift-windows-machine-config-operator-master-azure-e2e-operator/1458253671316852736/artifacts/azure-e2e-operator/gather-extra/artifacts/pods/openshift-machine-api_machine-api-controllers-577ddc7489-n8v7w_machine-controller.log)
We need to find a way to make this work with free and paid images
=> Revert "Bug 2021322: Azure Marketplace Purchase Plan Info"

pkg/apis/azureprovider/v1beta1/types.go, pkg/cloud/azure/services/virtualmachines/virtualmachines.go, pkg/cloud/azure/services/virtualmachines/virtualmachines_test.go
Manual backport of openshift/api#1057
Adding support for marketplace images.
=> Bug 2025697: API: Update Machine Provider Spec Image Type

.gitignore, vendor/sigs.k8s.io/cluster-api/util/kubeconfig/kubeconfig.go, vendor/sigs.k8s.io/cluster-api/util/kubeconfig/testing.go, vendor/sigs.k8s.io/kind/pkg/cluster/internal/kubeconfig/internal/kubeconfig/encode.go, vendor/sigs.k8s.io/kind/pkg/cluster/internal/kubeconfig/internal/kubeconfig/helpers.go, vendor/sigs.k8s.io/kind/pkg/cluster/internal/kubeconfig/internal/kubeconfig/lock.go, vendor/sigs.k8s.io/kind/pkg/cluster/internal/kubeconfig/internal/kubeconfig/merge.go, vendor/sigs.k8s.io/kind/pkg/cluster/internal/kubeconfig/internal/kubeconfig/paths.go, vendor/sigs.k8s.io/kind/pkg/cluster/internal/kubeconfig/internal/kubeconfig/read.go, vendor/sigs.k8s.io/kind/pkg/cluster/internal/kubeconfig/internal/kubeconfig/remove.go, vendor/sigs.k8s.io/kind/pkg/cluster/internal/kubeconfig/internal/kubeconfig/types.go, vendor/sigs.k8s.io/kind/pkg/cluster/internal/kubeconfig/internal/kubeconfig/write.go, vendor/sigs.k8s.io/kind/pkg/cluster/internal/kubeconfig/kubeconfig.go
.gitignore excludes kubeconfig from vendor and breaks CI builds. I will put a patch upstream to have it included in next rebase.
=> UPSTREAM: <carry>: Don't ignore kubeconfig package in vendor

pkg/cloud/azure/actuators/machine/actuator.go, pkg/cloud/azure/actuators/machine/actuator_test.go, pkg/cloud/azure/errors.go
Manual cherry pick of https://github.com/openshift/machine-api-provider-azure/pull/11
In several CI examples linked within the BZ, we are seeing issues with the credentials just after they are created or rotated by the CCO. It looks like once the credentials are rotated they take a few minutes to propagate.
When the Machine already exists, this is fine because the exists call returns a 401 and we requeue.
If a new machine is added, at the moment, the invalid credentials cause it to go into a failed phase, even though, if we retried slightly later, it is likely the create would have succeeded.
This PR changes the behaviour so that 401 errors (ie the credentials you provided weren't valid) no longer fails create.
I think this is safe as we already have a number of checks in place around …
=> Bug 2047845: Requeue create on invalid credentials errors

.gitignore
This entity blocks adding coverage.go file in the vendor folder.
=> UPSTREAM: <carry>: remove "coverage.*" from gitignore

Makefile, api/v1beta1/azureclusteridentity_webhook.go, api/v1beta1/azureclusteridentity_webhook_test.go, api/v1beta1/types.go, azure/scope/identity.go, azure/scope/workload_identity.go, config/crd/bases/infrastructure.cluster.x-k8s.io_azureclusteridentities.yaml, config/manager/manager.yaml, config/rbac/service_account.yaml, scripts/kind-with-registry.sh, templates/test/ci/cluster-template-prow-workload-identity.yaml, templates/test/ci/patches/azureclusteridentity-azwi.yaml, templates/test/ci/prow-workload-identity/kustomization.yaml, test/e2e/azure_test.go, test/e2e/config/azure-dev.yaml, test/e2e/e2e_suite_test.go
xref: [CCO-320](https://issues.redhat.com//browse/CCO-320)
* Enhancement proposal: https://github.com/openshift/enhancements/pull/1301
Base commit: 5f39919bc40e39922f75744cdbb86b9d494fdf1c (taken from upstream https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/3583)
=> CCO-320: Add support for Azure workload identity tokens

.gitignore, vendor/github.com/subosito/gotenv/.env
Image build was failing on Konflux due to missing go mod dependencies.
```
2025-04-04 17:29:55,704 INFO Vendoring the gomod dependencies
2025-04-04 17:30:10,676 ERROR vendor directory changed after vendoring:
A	vendor/github.com/subosito/gotenv/.env
2025-04-04 17:30:13,836 ERROR PackageRejected: The content of the vendor directory is not consistent with go.mod. Please check the logs for more details.
```
Konflux ignores .gitignore files since its a possible security gap.
=> ART-12521: update go mod dependency for konflux
